api_platform:
    title: Devish Assessment API
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true


    collection:
        pagination:
            enabled: true
        order: desc
