version: '3'

services:
  php:
    build:
      context: .
      dockerfile: /docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://devish:devish@db:5432/devish
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: devish
      POSTGRES_USER: devish
      POSTGRES_PASSWORD: devish

  webserver:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app/public
    ports:
      - "9090:80" # Map port 9090 on your host to port 80 in the container
    depends_on:
      - php

  composer:
    image: composer:2
    volumes:
      - .:/app
    working_dir: /app
    command: composer install --ignore-platform-reqs
